spring.application.name=back

logging.level.org.springframework.cache=TRACE

# MariaDB configuration
spring.datasource.url=jdbc:mariadb://localhost:3307/back_db
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

# Server port
server.port=8080

# IGDB configuration
igdb.client-id=${IGDB_CLIENT_ID}
igdb.client-secret=lieplkia5su578ci5e5f3tgfk1t8z4

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-expiration=2592000000

# Activer les tâches planifiées
spring.task.scheduling.pool-size=2
spring.task.scheduling.thread-name-prefix=scheduled-

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true

# Cache Caffeine
spring.cache.type=caffeine
spring.cache.cache-names=recherches-igdb
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m

# Avatar
avatar.upload-dir=uploads/avatars
avatar.base-url=http://localhost:8080/avatars
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB



