spring.application.name=back

# MariaDB configuration
spring.datasource.url=jdbc:mariadb://localhost:3307/back_db
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

# Server port
server.port=8080
